merge into 1 action

diff --git a/.github/actions/get_resource_by_id/action.yml b/.github/actions/get_resource_by_id/action.yml
--- a/.github/actions/get_resource_by_id/action.yml
+++ b/.github/actions/get_resource_by_id/action.yml
@@ -29,7 +29,7 @@ inputs:
         default: ''
 outputs:
   resource-id:
-    description: 'Resource id'
+    description: 'Resource id'    
     value: ${{ steps.retrieve-dns-name.outputs.resource-id }}
 runs:
   using: 'composite'
@@ -39,36 +39,63 @@ runs:
       run:  |  
         tagKey=${{ inputs.resource-tag-name }}
         tagValue=${{ inputs.resource-tag-value }}
+        resourceName=${{ inputs.resource-name }}
 
-        if [ -z "${{ inputs.resource-name }}" ]; then
-            # Retrieve by tag
-            load_balancer_arns=$(aws elbv2 describe-load-balancers --query 'LoadBalancers[*].LoadBalancerArn' --region ${{ inputs.aws-region }} --output text)
+        if [ "${{ inputs.resource-type }}" == 'ALB' ]; then
+          if [ -z "${{ inputs.resource-name }}" ]; then
+              # Retrieve by tag
+              load_balancer_arns=$(aws elbv2 describe-load-balancers --query 'LoadBalancers[*].LoadBalancerArn' --region ${{ inputs.aws-region }} --output text)
 
-            # Step 2: Find the load balancer ARN by tag name
-            for arn in $load_balancer_arns; do
-                 tags=$(aws elbv2 describe-tags --resource-arns $arn --query 'TagDescriptions[0].Tags' --region ${{ inputs.aws-region }} --output json)
-                
-                name=$(echo $tags | jq -r --arg TAG_KEY "$tagKey" --arg TAG_VALUE "$tagValue" '.[] | select(.Key == $TAG_KEY and .Value == $TAG_VALUE) | .Value')
+              # Step 2: Find the load balancer ARN by tag name
+              for arn in $load_balancer_arns; do
+                  tags=$(aws elbv2 describe-tags --resource-arns $arn --query 'TagDescriptions[0].Tags' --region ${{ inputs.aws-region }} --output json)
+                  
+                  name=$(echo $tags | jq -r --arg TAG_KEY "$tagKey" --arg TAG_VALUE "$tagValue" '.[] | select(.Key == $TAG_KEY and .Value == $TAG_VALUE) | .Value')
 
-                  if [ "${name}" == "${tagValue}" ]; then
-                      load_balancer_arn=$arn
-                      break
-                  fi
-                
-            done
+                    if [ "${name}" == "${tagValue}" ]; then
+                        load_balancer_arn=$arn
+                        break
+                    fi
+                  
+              done
 
-            # Check if the load balancer ARN was found
-            if [ -z "$load_balancer_arn" ]; then
-              echo "Load balancer with tag ${tagKey}=${tagValue} not found."
-              exit 1
-            fi
+              # Check if the load balancer ARN was found
+              if [ -z "$load_balancer_arn" ]; then
+                echo "Load balancer with tag ${tagKey}=${tagValue} not found."
+                exit 1
+              fi
 
-            # Step 3: Retrieve the DNS name of the load balancer
-            dns_name=$(aws elbv2 describe-load-balancers --load-balancer-arns "$load_balancer_arn" --query 'LoadBalancers[0].DNSName' --region ${{ inputs.aws-region }} --output text)
-            echo "DNS name by tag name:-$dns_name"
+              # Step 3: Retrieve the DNS name of the load balancer
+              dns_name=$(aws elbv2 describe-load-balancers --load-balancer-arns "$load_balancer_arn" --query 'LoadBalancers[0].DNSName' --region ${{ inputs.aws-region }} --output text)
+              echo "DNS name by tag name:-$dns_name"
+          else
+              dns_name=$(aws elbv2 describe-load-balancers --names ${{ inputs.resource-name }} --region ${{ inputs.aws-region }}| jq -r '.LoadBalancers[0].DNSName')
+              echo "DNS name by ALB name:-$dns_name"
+          fi;
+          echo "resource-id=$dns_name">> "$GITHUB_OUTPUT" 
         else
-            dns_name=$(aws elbv2 describe-load-balancers --names ${{ inputs.resource-name }} --region ${{ inputs.aws-region }}| jq -r '.LoadBalancers[0].DNSName')
-            echo "DNS name by ALB name:-$dns_name"
-        fi;
-        echo "resource-id=$dns_name">> "$GITHUB_OUTPUT" 
+          if [ -z "${{ inputs.resource-name }}" ]; then
+            # Retrieve by tag
+            hosted_zone_ids=$(aws route53 list-hosted-zones --query 'HostedZones[*].Id' --output text)         
+
+            # Step 2: Find the hosted zone by its tag
+            for temp_id in $hosted_zone_ids; do
+                 id=$(echo $temp_id | sed 's#/hostedzone/##')
+                 tag=$(aws route53 list-tags-for-resource --resource-type hostedzone --resource-id $id  --query ResourceTagSet.Tags[?Key==\`${tagKey}\`] --output text)
+
+                 echo "Output tag value-${tag}"
+                               
+                if [[ "$tag" == *${tagValue}* ]]; then
+                  hostedzone_id=$id
+                  break;
+                fi 
+            done
+          else
+              hostedzone_id_temp=$(aws route53 list-hosted-zones --query HostedZones[?Name==\`${resourceName}\`].Id --output text)
+              hostedzone_id=$(echo $hostedzone_id_temp | sed 's#/hostedzone/##')
+              echo "HostedZone-$hostedzone_id"              
+          fi;
+          echo "Resource-id:$hostedzone_id"
+          echo "resource-id=$hostedzone_id">> "$GITHUB_OUTPUT" 
+        fi;        
       shell: bash
