Formatted.

diff --git a/.github/actions/get_resource_by_id/action.yml b/.github/actions/get_resource_by_id/action.yml
--- a/.github/actions/get_resource_by_id/action.yml
+++ b/.github/actions/get_resource_by_id/action.yml
@@ -43,19 +43,19 @@ runs:
             
             # Step 2: Find the load balancer ARN by tag name
             for arn in $load_balancer_arns; do
-            tags=$(aws elbv2 describe-tags --resource-arns $arn --query 'TagDescriptions[0].Tags' --region ${{ inputs.aws-region }} --output json)
-            name=$(echo $tags | jq -r --arg TAG_KEY "${{ inputs.resource-tag-name }}" --arg TAG_VALUE "${{ inputs.resource-tag-value }}" '.[] | select(.Key == ${{ inputs.resource-tag-name }} and .Value == ${{ inputs.resource-tag-value }}) | .Value')
+                tags=$(aws elbv2 describe-tags --resource-arns $arn --query 'TagDescriptions[0].Tags' --region ${{ inputs.aws-region }} --output json)
+                name=$(echo $tags | jq -r --arg TAG_KEY "${{ inputs.resource-tag-name }}" --arg TAG_VALUE "${{ inputs.resource-tag-value }}" '.[] | select(.Key == ${{ inputs.resource-tag-name }} and .Value == ${{ inputs.resource-tag-value }}) | .Value')
             
-            if [ "$name" == "${{ inputs.resource-tag-value }}" ]; then
-                load_balancer_arn=$arn
-                break
-            fi
+                if [ "$name" == "${{ inputs.resource-tag-value }}" ]; then
+                    load_balancer_arn=$arn
+                    break
+                fi
             done
 
             # Check if the load balancer ARN was found
             if [ -z "$load_balancer_arn" ]; then
-            echo "Load balancer with tag ${{ inputs.resource-tag-name }}=${{ inputs.resource-tag-value }} not found."
-            exit 1
+              echo "Load balancer with tag ${{ inputs.resource-tag-name }}=${{ inputs.resource-tag-value }} not found."
+              exit 1
             fi
 
             # Step 3: Retrieve the DNS name of the load balancer
