Updated db workflow

diff --git a/.github/workflows/db.yml b/.github/workflows/db.yml
--- a/.github/workflows/db.yml
+++ b/.github/workflows/db.yml
@@ -27,21 +27,35 @@ jobs:
           # aws rds describe-db-instances --region $AWS_REGION --query DBInstances --output text | grep -oE 'pocdb1'
           psql -h $RDS_HOST -p $RDS_PORT -U $RDS_USERNAME
 
+      - name: Iterate through Migration folder
+        run: |
+          # Check if the target is not a directory
+          if [ ! -d "$MIGRATION_FOLDER" ]; then
+            exit 1
+          fi
+          
+          # Loop through files in the target directory
+          for file in "$directory"/*; do
+            if [ -f "$file" ]; then
+              echo "$file"
+            fi
+          done
+
       - name: Run migration script
         id: migration_script
         continue-on-error: true 
         run: |
           psql -h $RDS_HOST -d poc -p $RDS_PORT -U $RDS_USERNAME -f "create_table.sql"
       
-      - name: Rollback script
-        if: steps.migration_script.outcome == 'failure'
-        run: |
-         psql -h $RDS_HOST -d poc -p $RDS_PORT -U $RDS_USERNAME 
-         rollback;
+      # - name: Rollback script
+      #   if: steps.migration_script.outcome == 'failure'
+      #   run: |
+      #    psql -h $RDS_HOST -d poc -p $RDS_PORT -U $RDS_USERNAME 
+      #    rollback;
         
-      - name: Commit script
-        if: steps.migration_script.outcome == 'success'
-        run: |
-         psql -h $RDS_HOST -d poc -p $RDS_PORT -U $RDS_USERNAME 
-         commit;
+      # - name: Commit script
+      #   if: steps.migration_script.outcome == 'success'
+      #   run: |
+      #    psql -h $RDS_HOST -d poc -p $RDS_PORT -U $RDS_USERNAME 
+      #    commit;
       
